/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 jordan.gltf --transform
Author: makoto (https://sketchfab.com/lu87813)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/air-jordan-1-a4b434181fbb48008ad460722fd53725
Title: Air Jordan 1
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/jordan-transformed.glb');
  const group = useRef(null);
  useFrame(() => {
    if (!group.current) {
      return;
    }
    group.current.rotation.y += -0.003;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.shoe_shoe_0.geometry} material={materials.shoe} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.shoelace_shoelace_0.geometry} material={materials.shoelace} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/jordan-transformed.glb')
