import Head from 'next/head';
import styles from "../../styles/Categories/CategoryId.module.css";
import { Box } from '@mui/material';
import ImageWithFallback from "../../src/utils/ImageWithFallback";
import ProductBox from "../../src/utils/ProductBox";
import { useQuery } from "react-query";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

function Category({ category }: any) {
    const { data,isLoading } = useQuery(['GetProductsByCategory',category[0].category.id], () => fetcher(`https://api.escuelajs.co/api/v1/categories/${category[0].category.id}`));
    
    if (isLoading ) return <div>Loading...</div>;

    return (
        <div style={{ marginTop: "50px" }}>
            <Head>
                <title>{category[0].category.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="description" content="its my mobit clone" />
                <link rel="icon" href="/gta-home-logo.jpg" />
            </Head>
            <div>
                <div style={{ margin: "auto", width: "fit-content" }}>
                    <h1 className={styles.label}>{data?.name}</h1>
                    <div style={{ position: "relative", width: "90vw", height: "60vw", borderRadius: "10px", overflow: "hidden" }}>
                        <ImageWithFallback layout="fill" priority src={data?.image} alt={data?.name} />
                    </div>
                </div>
                <p style={{ width: "70vw", margin: "20px auto" }}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam odit nostrum officiis sunt voluptate fugiat, dolores reprehenderit ut doloribus totam ex perferendis sapiente ipsa tempore repellat reiciendis aperiam amet? Hic.</p>
                <div className={styles.productCategory}>
                    {category?.map((item: any) => (
                        <Box key={item.id} dir='rtl'>
                                <ProductBox item={item} />
                        </Box>
                    ))}
                </div>
            </div>
        </div>
        );
}

export default Category;

export async function getStaticPaths() {
    return {
            paths: [
        {
            params: {categoryId: 'Clothes' }
            },
        {
            params: {categoryId: 'Electronics' }
            },
        {
            params: {categoryId: 'Furniture' }
            },
        {
            params: {categoryId: 'Shoes' }
            },
        {
            params: {categoryId: 'Others' }
            },
        ],
        fallback: false,
    }
}

export async function getStaticProps(context: any) {
    const {params} = context;

        let id;
        switch (params.categoryId) {
        case "Clothes":
        id = 1;
        break;
        case "Electronics":
        id = 2;
        break;
        case "Furniture":
        id = 3;
        break;
        case "Shoes":
        id = 4;
        break;
        case "Others":
        id = 5;
        break;
    }
        const response = await fetch(`https://api.escuelajs.co/api/v1/categories/${id}/products`)
        const data = await response.json();

        return {
            props: {
            category: data,
        },
    }
}