import Head from 'next/head';
import dynamic from 'next/dynamic'
import styles from "../../styles/Products/Product.module.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import MenuBookIcon from '@mui/icons-material/MenuBook';
import BasicSpeedDial from "../../components/ProductPage/SpeedDial";
import ReadMore from "../../components/ProductPage/ReadMore";
import Useless from "../../components/ProductPage/Useless";
import AddCart from "../../components/ProductPage/AddCart";
import SimilarItems from "../../components/ProductPage/SimilarItems";
import SubNav from "../../components/ProductPage/SubNav";
import axios from 'axios';
import Detail from '../../components/ProductPage/Detail';
import DescAddCart from '../../components/ProductPage/DescAddCart';
import DescDetail from '../../components/ProductPage/DescDetail';

const Intro = dynamic(
    () => import('../../components/ProductPage/Slider'),
    { loading: () => <p>Loading caused by client page transition ...</p>, ssr: false }
);

function Product({ product }: any) {
    const colors = ["white", "blue", "pink"];
    const [rating, setRating] = useState(1);
    const [width, setWidth] = useState(200);
    const [color, setColor] = useState(colors[0]);

    console.log(width);

    useEffect(() => {
        setRating(() => Math.floor(Math.random() * (40) + 10) / 10);
    }, []);

    // mock data i use to readmore section
    const title = `about ${product.title}`
    const readmore = `${product.description}Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora esse, tempore aspernatur, eveniet quos beatae, ipsam explicabo non omnis voluptatum numquam fuga quisquam. Impedit architecto cupiditate deserunt assumenda deleniti nostrum.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora esse, tempore aspernatur, eveniet quos beatae, ipsam explicabo non omnis voluptatum numquam fuga quisquam. Impedit architecto cupiditate deserunt assumenda deleniti nostrum.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora esse, tempore aspernatur, eveniet quos beatae, ipsam explicabo non omnis voluptatum numquam fuga quisquam. Impedit architecto cupiditate deserunt assumenda deleniti nostrum.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora esse, tempore aspernatur, eveniet quos beatae, ipsam explicabo non omnis voluptatum numquam fuga quisquam. Impedit architecto cupiditate deserunt assumenda deleniti nostrum.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora esse, tempore aspernatur, eveniet quos beatae, ipsam explicabo non omnis voluptatum numquam fuga quisquam. Impedit architecto cupiditate deserunt assumenda deleniti nostrum.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora esse, tempore aspernatur, eveniet quos beatae, ipsam explicabo non omnis voluptatum numquam fuga quisquam. Impedit architecto cupiditate deserunt assumenda deleniti nostrum.`
    return (<div style={{ marginBottom: 50 }}>
        {product ?
            <div>
                <Head>
                    <title>{product.title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="description" content="its my mobit clone" />
                    <link rel="icon" href="/gta-home-logo.jpg" />
                </Head>
                <div style={{ padding: "0 10px" }}>
                    <SubNav />
                    <div>
                        <div style={{ display: "dflex", justifyContent: "center", alignItems: "center" }}>
                            <div style={{ width: "12rem" }}>
                                {width >= 900 && <DescAddCart product={product} />}
                            </div>
                            <div>
                                <div className={styles.Intro}>
                                    <div style={{ width: "fit-content", margin: "20px auto" }}>
                                        <Link href={`/categories/${product.category.name}`}><h2 className={styles.category}>{product.category.name}</h2></Link>
                                        <Intro product={product} setWidth={setWidth} />
                                    </div>
                                    {
                                        width < 900 && <Detail product={product} color={color} setColor={setColor} rating={rating} setRating={setRating} colors={colors} />
                                    }
                                    {
                                        width >= 900 && <DescDetail product={product} color={color} setColor={setColor} rating={rating} setRating={setRating} colors={colors} />
                                    }
                                </div>
                                <div id="nav">
                                    <div id="one">
                                        <div style={{ background: "linear-gradient(270deg, transparent 10%, rgba(244,162,255,1) 100%)" }} className={styles.secIntro}>
                                            <MenuBookIcon sx={{ color: "white", margin: "10px" }} />About this item</div>
                                        <ReadMore text={[readmore, title]} />
                                        <ReadMore text={[readmore, title]} />
                                        <ReadMore text={[readmore, title]} />
                                    </div>
                                    <div id="two">
                                        <div style={{ background: "linear-gradient(270deg, transparent 10%, rgba(0,228,255,1) 100%)" }} className={styles.secIntro}>
                                            <MenuBookIcon sx={{ color: "white", margin: "10px" }} />Technical Details</div>
                                        <Useless />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="nav2">
                            <div id="three">
                                <h2 style={{ textAlign: "center" }}>Similar Items</h2>
                                <SimilarItems category={product.category.id} />
                            </div>
                        </div>
                    </div>
                </div>
                <BasicSpeedDial title={product.title} />
                {
                    width < 900 && <AddCart product={product} />
                }
            </div> :
            <div>
                wait...
            </div>}
    </div>
    );
}

export default Product;

export async function getServerSideProps(context: any) {
    const { params } = context;
    const response = await axios.get(`https://api.escuelajs.co/api/v1/products/${params.id}`)
    return {
        props: {
            product: response.data,
        },
    }
}