import Link from 'next/link';
import Head from 'next/head';
import Button from "@mui/material/Button";
import Image from 'next/image';

function NotFound() {
    return (<div style={{ minHeight: "120vh" }}>
        <Head>
            <title>Page Not Found</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="description" content="its my mobit clone" />
            <link rel="icon" href="/gta-home-logo.jpg" />
        </Head>
            <h1 style={{ textAlign: "center", fontSize: "7vw" }}>Page Not Found</h1>
            <div style={{ position: "relative", width: "40vw", height: "40vw", margin: "auto" }}>
                <Image src="https://www.mobit.ir/_nuxt/img/error-404.0f46f2e.svg" priority layout="fill" alt="404page" />
            </div>
            <div style={{ width: "100vw" }}>
                <Button sx={{ margin: "auto", backgroundColor: "info.main", "&:hover": { backgroundColor: "grey.900" }, color: "white", width: "30vw", position: "absolute", left: 0, right: 0, padding: "7px" }}>
                    <Link href="/">
                        <a>
                            <h3 style={{ margin: 0 }}>Go back home</h3>
                        </a>
                    </Link>
                </Button>
            </div>
    </div>);
}

export default NotFound;