import Head from 'next/head';
import Intro from '../components/Index/Intro';
import Category from '../components/Index/Category';
import MissingIntro from '../components/Index/MissingIntro';
import OfferProducts from '../components/Main/OfferProducts';

const Home = ({host}:{host:string}) => {

  return (
    <>
      <Head>
        <title>gta home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="description" content="its my mobit clone" />
        <link rel="icon" href="/gta-home-logo.jpg" />
      </Head>
      <Intro host={host} />
      <Category />
      <MissingIntro host={host} />
      <OfferProducts />
    </>
  )
}

export default Home

export async function getServerSideProps(context: any) {
  const  host  = context.req.headers.host;
  return {
      props: {
        host
      }
  }
}
