import type { NextPage } from 'next';
import Head from 'next/head';
import Intro from '../components/Headers/Intro';
import Category from '../components/Headers/Category';
import MissingIntro from '../components/Headers/MissingIntro';
import OfferProducts from '../components/Main/OfferProducts';
import Link from 'next/link';

const Home: NextPage = () => {
  
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gta-home-logo.jpg" />
      </Head>
      <Intro />
      <Category />
      <MissingIntro />
      <OfferProducts />
      <Link href='./contact-us'>contact</Link>

    </div>
  )
}

export default Home
