import React, { Suspense } from "react";
import Cookies from "js-cookie";
import { Paper, IconButton } from "@mui/material";
import Head from "next/head";
import { useForm } from "react-hook-form";
import CustomInput from "../src/Mui/TextField";
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';
import { useRouter } from 'next/router';
import Link from "next/link";
import { yupResolver } from '@hookform/resolvers/yup';
import * as Yup from 'yup';
import styles from '../styles/Login/Login.module.css';
import Button from '@mui/material/Button';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogTitle from '@mui/material/DialogTitle';
import { Canvas } from "@react-three/fiber";
import { OrbitControls, Stage, Html, useProgress } from "@react-three/drei";
import Model from "../components/Login/Jordan";

function Loader() {
    const { active, progress, errors, item, loaded, total } = useProgress();
    return <Html center>{progress} % loaded</Html>;
}

type UserSubmitForm = {
    email: string;
    password: string;
};

function Login() {
    const [visible, setVisible] = React.useState(false);
    const [open, setOpen] = React.useState(false);
    const router = useRouter();

    const validationSchema = Yup.object().shape({
        email: Yup.string()
            .required('ایمیل الزامی است.')
            .email('ایمیل نامعتبر است.'),
        password: Yup.string()
            .required('رمز عبور الزامی است.')
            .min(8, 'پسورد کوتاه است حداقل 8 کاراکتر')
            .max(20, 'پسورد طولانی است حداکثر 20 کاراکتر'),
    });

    const {
        register,
        handleSubmit,
        formState: { errors },
        reset,
    } = useForm<UserSubmitForm>(
        {
            resolver: yupResolver(validationSchema),
        }
    );

    const onSubmit = async (data: any) => {
        try {
            const response = await fetch('https://api.dotenx.com/user/management/project/uXcyPyNEbyI6Bdd4/login', {
                method: 'POST',
                body: JSON.stringify(data)
            })
                .then(res => res.json())
            if (response.accessToken) {
                Cookies.set("accessToken", response.accessToken);
                Cookies.set("expirationTime", response.expirationTime);
                router.push('/dashboard');
            } else {
                setOpen(true);
            }
        } catch {
            return
        }
        reset();
    }

    const handleMouseDownPassword = (event: React.MouseEvent<HTMLButtonElement>) => {
        event.preventDefault();
    };
    const handleClickShowPassword = () => { setVisible(!visible) };
    //customInput dosent assigned register
    const { ref: refemail, ...objemail } = register('email');
    const { ref: refpassword, ...objpassword } = register('password');

    const handleClose = () => {
        setOpen(false);
    };

    return (<section>
        <Head>
            <title>Login</title>
            <link rel="icon" href="/gta-home-logo.jpg" />
            <meta name="description" content="Generated by create next app" />
            <meta name="description" content="its my mobit clone" />
        </Head>
        <div className={styles.container}>
            <h1>GTA Home</h1>
            <Paper className={styles.paper} sx={{ backgroundColor: "grey" }}>
                <form onSubmit={handleSubmit(onSubmit)} dir="rtl" style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", marginTop: "30px" }}>
                    <CustomInput
                        variant="outlined"
                        type="email"
                        placeholder="ایمیل خود را وارد کنید..."
                        label="ایمیل"
                        color="info"
                        {...objemail}
                        inputRef={refemail}
                        autoComplete="email"
                        error={!!errors.email}
                        helperText={errors.email ? errors.email.message : null}
                        className={styles.input}
                    />
                    <div className={styles.passInput}>
                        <CustomInput
                            variant="outlined"
                            type={visible ? 'text' : 'password'}
                            placeholder="رمز ورود وارد کنید..."
                            label="رمز ورود"
                            color="info"
                            {...objpassword}
                            inputRef={refpassword}
                            error={!!errors.password}
                            helperText={errors.password ? errors.password.message : null}
                            sx={{ width: "100%" }}
                        />
                        <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            onMouseDown={handleMouseDownPassword}
                            sx={{ color: 'black', position: 'absolute', left: '12px', top: '9px' }}
                        >
                            {visible ? <VisibilityOff /> : <Visibility />}
                        </IconButton>
                    </div>
                    <div className={styles.btn}>
                        <Button type="submit" sx={{ "&:hover": { backgroundColor: 'primary.dark' }, display: "block", margin: 2, backgroundColor: 'primary.light', fontSize: "20px", width: "150px", color: "grey.A100" }} >ورود به حساب</Button>
                        <Link href="/signup" target="_blank"><Button sx={{ "&:hover": { backgroundColor: 'grey.500' }, display: "block", margin: 2, backgroundColor: 'grey.A400', fontSize: "20px", width: "150px", color: "grey.A100" }}>ثبت نام</Button></Link>
                    </div>
                </form>
                <div className={styles.Canvas} >
                    <Canvas style={{ width: "100%", height: "100%" }} shadows camera={{ position: [0, 0, -10] }}>
                        <Suspense fallback={<Loader />}>
                            <OrbitControls enableZoom={false} makeDefault minPolarAngle={Math.PI / 2.5} maxPolarAngle={Math.PI / 2.5} />
                            <Stage intensity={1.5} environment="dawn" adjustCamera={1.3}>
                                <Model scale={0.01} />
                            </Stage>
                        </Suspense>
                    </Canvas>
                </div>
            </Paper>
            <div>
                <Dialog
                    open={open}
                    onClose={handleClose}
                    aria-labelledby="alert-dialog-title"
                    aria-describedby="alert-dialog-description"
                    dir="rtl"
                >
                    <DialogTitle id="alert-dialog-title">
                        {"ایمیل یا رمز ورود اشتباه است."}
                    </DialogTitle>
                    <DialogContent>
                        <DialogContentText id="alert-dialog-description">
                            درصورتی که ایمیل یا رمز ورود خود را فراموش کرده اید متاسفانه دوباره ثبت نام کنید.
                        </DialogContentText>
                    </DialogContent>
                    <DialogActions>
                        <div style={{ margin: "auto" }}>
                            <Link href="/signup"><Button sx={{ backgroundColor: "grey.300", "&:hover": { backgroundColor: "grey.900" }, color: "info.main" }}><h4 style={{ margin: 0 }}>ثبت نام</h4></Button></Link>
                            <Button onClick={handleClose} autoFocus sx={{ backgroundColor: "grey.300", "&:hover": { backgroundColor: "grey.900" }, margin: "10px" }}><h4 style={{ margin: 0 }}>بازگشت</h4></Button>
                        </div>
                    </DialogActions>
                </Dialog>
            </div>
        </div>
    </section >);
}

export default Login;