import { Paper, Button, IconButton } from "@mui/material";
import Head from "next/head";
import { useForm } from "react-hook-form";
import CustomInput from "../src/Mui/TextField";
import Visibility from '@mui/icons-material/Visibility';
import VisibilityOff from '@mui/icons-material/VisibilityOff';
import React from "react";
import { yupResolver } from '@hookform/resolvers/yup';
import * as Yup from 'yup';
import styles from '../styles/signup/Signup.module.css';
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import AnimatedSphere from "../components/Login/AnimatedSphere";

type UserSubmitForm = {
    email: string;
    fullname: string;
    password: string;
    confirmPassword: string;
};

function Signup() {
    const [visible, setVisible] = React.useState(false)

    const validationSchema = Yup.object().shape({
        email: Yup.string()
            .required('ایمیل الزامی است.')
            .email('ایمیل نامعتبر است.'),
        fullname: Yup.string()
            .required('نام کاربری الزامی است.'),
        password: Yup.string()
            .required('رمز عبور الزامی است.')
            .min(8, 'پسورد کوتاه است حداقل 8 کاراکتر')
            .max(20, 'پسورد طولانی است حداکثر 20 کاراکتر'),
        confirmPassword: Yup.string()
            .label('confirm password')
            .oneOf([Yup.ref('password'), null], 'پسورد همخوانی ندارد')
            .required('فیلد الزامی است.')
    });

    const {
        register,
        handleSubmit,
        formState: { errors },
        reset,
    } = useForm<UserSubmitForm>(
        {
            resolver: yupResolver(validationSchema),
        }
    );

    const onSubmit = async (data: any) => {
        try {
            await fetch('https://api.dotenx.com/user/management/project/uXcyPyNEbyI6Bdd4/register', {
                method: 'POST',
                body: JSON.stringify(data)
            })
                .then(res => res.json())
        }
        catch (error: any) {
            throw new Error(`failed to signup ${error.message}`)
        }
        reset();
    }

    const handleMouseDownPassword = (event: React.MouseEvent<HTMLButtonElement>) => {
        event.preventDefault();
    };
    const handleClickShowPassword = () => { setVisible(!visible) };
    //customInput dosent assigned register
    const { ref: refemail, ...objemail } = register('email');
    const { ref: refpassword, ...objpassword } = register('password');
    const { ref: refconfirmPassword, ...objconfirmPassword } = register('confirmPassword');
    const { ref: reffullname, ...objfullname } = register('fullname');

    return (<section>
        <Head>
            <title>Sign up</title>
            <link rel="icon" href="/gta-home-logo.jpg" />
            <meta name="description" content="Generated by create next app" />
            <meta name="description" content="its my mobit clone" />
        </Head>
        <div className={styles.container}>
            <h1 style={{ textAlign: 'center' }}>GTA Home</h1>
            <div className={styles.sphere} style={{ height: "200px", width: "200px", position: "absolute", top: "120px",zIndex:-10 }}>
                <Canvas style={{ height: "100%" }}>
                    <OrbitControls enableZoom={false} makeDefault />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[-2, 5, 2]} intensity={1} />
                    <AnimatedSphere speed={3.5} color={"#8352FD"} scale={2.8} distort={0.3} />
                </Canvas>
            </div>
            <div style={{ height: "300px", width: "300px", position: "absolute", right: "60px", zIndex: -20 }}>
                <Canvas style={{ height: "100%" }}>
                    <OrbitControls enableZoom={false} />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[-2, 5, 2]} intensity={1} />
                    <AnimatedSphere speed={3.5} color={"orange"} scale={1.8} distort={0.6} />
                </Canvas>
            </div>
            <div style={{ height: "200px", width: "200px", position: "absolute", left: "0px", bottom: "0px", zIndex: -20 }}>
                <Canvas style={{ height: "100%" }}>
                    <OrbitControls enableZoom={false} />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[-9, 5, 2]} intensity={1} />
                    <AnimatedSphere speed={3.5} color={"red"} scale={1.5} distort={0.4} />
                </Canvas>
            </div>
            <div style={{ height: "200px", width: "200px", position: "absolute", right: "20px", top: "140px", zIndex: -20 }}>
                <Canvas style={{ height: "100%" }}>
                    <OrbitControls enableZoom={false} />
                    <ambientLight intensity={0.3} />
                    <directionalLight position={[12, 2, 7]} intensity={1} />
                    <AnimatedSphere speed={3.5} color={"#333"} scale={1.9} distort={0.5} />
                </Canvas>
            </div>
            <div style={{ height: "200px", width: "200px", position: "absolute", bottom: "10px", right: "10px", zIndex: -20 }}>
                <Canvas style={{ height: "100%" }}>
                    <OrbitControls enableZoom={false} />
                    <ambientLight intensity={0.5} />
                    <directionalLight position={[9, 9, 2]} intensity={1} />
                    <AnimatedSphere speed={3.5} color={"yellow"} scale={1.8} distort={0.3} />
                </Canvas>
            </div>
            <Paper className={styles.paper}>
                <form onSubmit={handleSubmit(onSubmit)} dir="rtl" style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
                    <CustomInput
                        variant="outlined"
                        type="email"
                        placeholder="ایمیل خود را وارد کنید..."
                        {...objemail}
                        inputRef={refemail}
                        error={!!errors.email}
                        helperText={errors.email ? errors.email.message : null}
                        color="info"
                        label="ایمیل "
                        autoComplete="email"
                        className={styles.input}
                    />
                    <CustomInput
                        variant="outlined"
                        type="text"
                        placeholder="نام کاربری خود را وارد کنید..."
                        label="نام کاربری"
                        color="info"
                        {...objfullname}
                        inputRef={reffullname}
                        autoComplete="fullname"
                        error={!!errors.fullname}
                        helperText={errors.fullname ? errors.fullname.message : null}
                        className={styles.input}
                    />
                    <div className={styles.passInput}>
                        <CustomInput
                            variant="outlined"
                            type={visible ? 'text' : 'password'}
                            placeholder="رمز ورود وارد کنید..."
                            label="رمز ورود"
                            color="info"
                            {...objpassword}
                            inputRef={refpassword}
                            error={!!errors.password}
                            helperText={errors.password ? errors.password.message : null}
                            sx={{ width: "100%" }}
                        />
                        <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            onMouseDown={handleMouseDownPassword}
                            sx={{ color: 'black', position: 'absolute', left: '12px', top: '9px' }}
                        >
                            {visible ? <VisibilityOff /> : <Visibility />}
                        </IconButton>
                    </div>
                    <div className={styles.passInput}>
                        <CustomInput
                            variant="outlined"
                            type={visible ? 'text' : 'password'}
                            placeholder="رمز ورود  دوباره ..."
                            label="تایید رمز ورود"
                            color="info"
                            {...objconfirmPassword}
                            inputRef={refconfirmPassword}
                            error={!!errors.confirmPassword}
                            helperText={errors.confirmPassword ? errors.confirmPassword.message : null}
                            sx={{ width: "100%" }}
                        />
                        <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            onMouseDown={handleMouseDownPassword}
                            sx={{ color: 'black', position: 'absolute', left: '12px', top: '9px' }}
                        >
                            {visible ? <VisibilityOff /> : <Visibility />}
                        </IconButton>
                    </div>
                    <Button type="submit" sx={{ "&:hover": { backgroundColor: 'primary.dark' }, display: "block", margin: 2, backgroundColor: 'primary.light', fontSize: "20px", width: "200px", color: "grey.A100" }} >ایجاد حساب</Button>
                </form>
            </Paper>
        </div>
    </section>);
}

export default Signup;